### ISSUE TITLE
Abstract methods in TuneRectangle should be documented with Javadoc

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamuno#46] opened 2019-04-18 04:04 UTC
https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamuno/blob/256287ae65f9a25c20f8ccad76ec990698d916cc/src/tunecomposer/TuneRectangle.java#L22

**Comment by beszel** [comment] 2019-04-23 02:43
Duplicate of the more general #56

**Closed as completed by beszel** 2019-04-23 02:43 UTC
